# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Favorite.delete_all
Game.delete_all
User.delete_all

games =
         [{title: "BATTLEFIELD", price: 29, description: "First person shooter game, developed by Dice and published by EA .", link: "https://www.origin.com/usa/en-us/store/battlefield/battlefield-v", image:"https://i2-prod.dailystar.co.uk/tech/gaming/article22249826.ece/ALTERNATES/s1200c/0_battlefield-v.jpg", category:"PC, PS4 and Xbox X"},
         {title: "GOD OF WAR", price: 25, description: "Based in ancient mythology, the story follows Kratos, a Spartan warrior who was tricked into killing his family by his former master, the Greek God of War Ares. This sets off a series of events that leads to wars with the mythological pantheons.", link: "https://store.playstation.com/en-us/product/UP9000-CUSA07408_00-00000000GODOFWAR", image: "https://images-na.ssl-images-amazon.com/images/I/91VKfyGGkYL._SY445_.jpg", category:"Action-Advanture"},
         {title: "Need For Speed: Origin", price: 27, description: "If you have a knack for underground car racing and you aren't afraid of ending up being chased in a hot pursuit, Need For Speed is the game for you. Several types of challenges, online seamless multiplayer, and a story mode are what you need to relive some of the best racing moments you've seen in movies", link: "https://www.g2a.com/need-for-speed-origin-key-global-i10000001907003?adid=&id=45&gclid=CjwKCAjwiOv7BRBREiwAXHbv3G62_2xsSGQd8R5ZBoXlCd0wCtq30-9TKFRi8_OaMkcUZfWrUpouNhoC8dsQAvD_BwE&gclsrc=aw.ds", image: "https://originassets.akamaized.net/origin-com-store-final-assets-prod/185353/231.0x326.0/1024486_LB_231x326_en_US_%5E_2015-08-04-10-45-42_0f314b68e981580a1416ef0d36679e0b0608e560.jpg", category:"Rasing-Action"},
         {title: "Dark Souls III", price: 55, description: "Dark Souls III was critically and commercially successful, with critics calling it a worthy and fitting conclusion to the series.", link: "https://store.playstation.com/en-us/product/UP0700-CUSA03388_00-DARKSOULS3000000?emcid=se-pi-230663&gclid=CjwKCAjwiOv7BRBREiwAXHbv3NXP5376rhNmIDJXS0r8YuNvvjza3NvXzZrwaec0AqtJhRN8TFqGMhoCwUsQAvD_BwE", image: "https://store.playstation.com/store/api/chihiro/00_09_000/container/US/en/999/UP0700-CUSA03388_00-DARKSOULS3000000/1601165321000/image?w=240&h=240&bg_color=000000&opacity=100&_version=00_09_000", category:"Action-Advanture"},
         {title: "GTA V", price: 20, description: "is a video game developed by Rockstar North. It is the fifteenth installment in the Grand Theft Auto series and the successor of Grand Theft Auto IV.", link: "https://store.playstation.com/en-us/product/UP1004-CUSA00419_00-GTAVDIGITALDOWNL?emcid=se-pi-230663&gclid=CjwKCAjwiOv7BRBREiwAXHbv3BYZdhlPtODMymNSZ29nPjpfoHdtEGVKYlmovZ9t7Lsqg51a9Q52eBoCLqcQAvD_BwE", image: "https://cdn.cdkeys.com/500x706/media/catalog/product/g/r/grand_theft_auto_v_5_gta_5_pc_3.jpg", category:"Action"},
         {title: "Apex", price: 0, description: "Choose from a lineup of outlaws, soldiers, misfits, and misanthropes, each with their own set of skills. The Apex Games welcome all comers – survive long enough, and they call you a Legend", link: "https://www.ea.com/games/apex-legends", image: "https://assets1.ignimgs.com/2019/02/04/apex-legends---button-fin-1549319070496.jpg", category:"FPS, Battle Royal"},
         {title: "FIFA 20", price: 40, description: "Best football experience", link: "https://www.g2a.com/search?id=45&adid=&query=FIFA&gclid=CjwKCAjwiOv7BRBREiwAXHbv3IJ95DEP11b4Onc4f6WPYxxnQTXTv9dNMhXCaRUf5gDrIEFCv-o9sRoCNBIQAvD_BwE&gclsrc=aw.ds", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcROidMOJD1ODwrJacQT0JkVvjuXtGnIca_HsQ&usqp=CAU", category:"Sport"},
         {title: "Super Mario bros.", price: 10, description: "is a platform video game developed and published by Nintendo.Players control Mario, or his brother Luigi in the multiplayer mode, as they travel the Mushroom Kingdom to rescue Princess Toadstool from Bowser (King Koopa).", link: "https://www.target.com/p/super-mario-3d-all-stars-nintendo-switch/-/A-80898570?ref=tgt_adv_XS000000&AFID=google_pla_df&fndsrc=tgtao&CPNG=PLA_Video%2BGames%2BShopping&adgroup=SC_Video%2BGames&LID=700000001170770pgs&network=g&device=c&location=9028794&ds_rl=1246978&ds_rl=1248099&gclid=CjwKCAjwiOv7BRBREiwAXHbv3LmrowLx3cqtFcACtrHQdlIqWTJnBE_krP3zjHA0FHUhE4_WZBH65xoCR0AQAvD_BwE&gclsrc=aw.ds", image: "https://www.mariowiki.com/images/thumb/2/25/Mario_New_Super_Mario_Bros_U_Deluxe.png/200px-Mario_New_Super_Mario_Bros_U_Deluxe.png", category:"Action-Advanture"},
         {title: "WORLD OF WARCRAFT", price: 77, description: "is a massively multiplayer online role-playing game (MMORPG) released in 2004 by Blizzard Entertainment. It is the fourth released game set in the Warcraft fantasy universe.", link: "https://us.shop.battle.net/en-us/product/world-of-warcraft-subscription?utm_source=Google&utm_medium=Search&utm_content=29732128&utm_campaign=BLZ_WoW_EG_Modern-Classic_UA_2020_NA", image: "https://static-cdn.jtvnw.net/ttv-boxart/World%20of%20Warcraft.jpg", category:"RPG-MMO"},
         
     ]

games.each do |game|
  Game.create(game)
end